[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改学生上课信息"]bar.addBack();[/@]
[@b.form action=b.rest.save(taker) theme="list"]
  [@b.field label="学年学期"]${taker.lesson.semester.schoolYear}学年度${taker.lesson.semester.name}学期[/@]
  [@b.field label="课程"]${taker.lesson.crn} ${taker.lesson.course.name} ${taker.lesson.openOn!} ${taker.lesson.beginAt!}[/@]
  [@b.radios style="width:100px" name="taker.passed" value=taker.passed!'' label="是否完成" items={"1":"是", "0":"否","":"考核中"} /]
  [@b.textarea name="taker.remark" label="备注" value=taker.remark! required="false" maxlength="300" rows="4" cols="70"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[@b.foot/]
