[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改劳动教育开课信息"]bar.addBack();[/@]
[@b.form action=b.rest.save(lesson) theme="list"]
  [@b.field label="学年学期"]${lesson.semester.schoolYear}学年度${lesson.semester.name}学期[/@]
  [@b.textfield name="lesson.crn" label="课程序号" value=lesson.crn! required="true" maxlength="20"/]
  [@b.textfield name="lesson.subject" label="课程主题" value=lesson.subject! required="false" maxlength="200"/]
  [@b.select name="lesson.course.id" label="课程" value=lesson.course! items=courses required="true" empty="..."/]
  [@b.select name="grade.id" label="年级" values=lesson.grades items=grades required="false" empty="..." multiple="true"/]
  [@b.textfield name="lesson.capacity" label="人数上限" value=lesson.capacity required="true"/]
  [@b.date name="lesson.openOn" label="开课日期"  value=lesson.openOn! required="true"/]
  [#if lesson.id??]
  [@b.startend name="lesson.beginAt,lesson.endAt" label="上课时间" start=lesson.beginAt! end=lesson.endAt! format="HH:mm" required="true,true"/]
  [#else]
  [@b.startend name="lesson.beginAt,lesson.endAt" label="上课时间" format="HH:mm" required="true,true"/]
  [/#if]
  [@b.textfield name="lesson.teachers" label="授课老师" value=lesson.teachers! required="false" maxlength="100"/]
  [@b.textfield name="lesson.locations" label="上课地点" value=lesson.locations! required="false" maxlength="200"/]
  [@b.startend name="lesson.chooseBeginAt,lesson.chooseEndAt" label="选课时间" start=lesson.chooseBeginAt! end=lesson.chooseEndAt! format="yyyy-MM-dd HH:mm:ss" required="false,false"/]
  [@b.textarea name="lesson.remark" label="备注" value=lesson.remark! required="false" maxlength="300" rows="4" cols="70"/]
  [@b.formfoot]
    <input type="hidden" name="lesson.semester.id" value="${lesson.semester.id}"/>
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
  [/@]
[/@]
[@b.foot/]
